language: node_js
services: mongodb
node_js:
    - 8
    - 'stable'
before_install:
    - npm install -g coveralls
install:
    - npm install
script:
    - cp .env.example .env
    - sed -i 's/JWT_SECRET=/JWT_SECRET=test/g' .env
    - npm run lint
    - npm run cover:check
after_success:
    - cat ./_dev/cover/lcov.info | coveralls
